[package]
name = "MarketClient"
version = "0.1.0"
authors = ["ming"]
edition = "2018"

[dependencies]
paho-mqtt = "0.5.0"
influx_db_client = "0.3.6"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }